server:
  tomcat:
    basedir: /var/tmp/
    uri-encoding: UTF-8
    threads:
      max: 0
    remoteip:
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 30s

spring:
  profiles:
    active: local
  application:
    name: minesite
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
  freemarker:
    cache: true
    suffix: .ftl
    prefer-file-system-access: false
    settings:
      number_format: 0.##
  aop:
    auto: true
  messages:
    basename: i18n/message
  datasource:
    # com.alibaba.druid.filter.config.ConfigTools.main(new String[]{"password"})
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #下面为连接池补充设置
      initialSize: 5
      # 配置获取连接等待超时的时间   
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒 
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      # 合并多个DruidDataSource的监控数据 
      useGlobalDataSourceStat: true
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
        slf4j:
          enabled: true
        config:
          enabled: true
      connectionProperties: config.decrypt=true;config.decrypt.key=${minesite.druid.key}
      stat-view-servlet:
        reset-enable: true
        url-pattern: "/druid/*"
        login-username: ${minesite.druid.username}
        login-password: ${minesite.druid.password}
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: "/*"
  quartz:
    #数据库方式
    job-store-type: jdbc
    jdbc:
      #不初始化表结构
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
            instanceId: AUTO
            #instanceName: clusteredScheduler #quartzScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
            useProperties: false #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
            tablePrefix: QRTZ_  #数据库表前缀
            misfireThreshold: 60000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
            clusterCheckinInterval: 5000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
            isClustered: true #打开群集功能
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

logging:
  config: classpath:logback-files.xml

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

minesite:
  version:
    base: 3
