server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/minesite?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: pwd

#  freemarker:
#    cache: true

logging:
  config: classpath:logback-files.xml

minesite:
  username: admin
  druid:
    key: root
    username: druid
    password: druid
  login:
    seconds: 3600
    sign: dksk24k30xk
