server:
  tomcat:
    basedir: /var/tmp/
    max-threads: 0
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  forward-headers-strategy: native
  servlet:
    context-path: /api
    session:
      timeout: 30s

spring:
  profiles:
    active: local
  application:
    name: minesite-web
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
  jackson:
    serialization:
      write-dates-as-timestamps: true
  freemarker:
    prefer-file-system-access: false
  aop:
    auto: true
  messages:
    basename: i18n/message
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
