server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/minesite?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: pwd

minesite:
  version:
    app: 1
  druid:
    key: root
    username: druid
    password: druid
  login:
    seconds: 3600
    sign: dksk24k30xk
  dingtalk:
    token: 1
  telegram:
    key: 2
